// PRD §25 — "Every state transition, every tool call..., every LLM invocation...,
// every validator run, and every human action is appended as an immutable
// AuditEvent... The audit trail is the single source the Mission Control
// 'timeline' view renders from — nothing shown in the UI is allowed to exist
// without a corresponding AuditEvent."
import type { AuditEvent } from "@nexus/shared/types/audit";
import { Panel } from "./Panel";
import { StatusPill, toolResultTone } from "./StatusPill";
import { formatTimeUTC, toolCallLabel } from "@/lib/missionControl/format";

function isToolStatus(value: unknown): value is "SUCCESS" | "FAILURE" | "NO_DATA" {
  return value === "SUCCESS" || value === "FAILURE" || value === "NO_DATA";
}

// Display-only: TOOL_CALL summaries are generated by shared/tools/dispatch.ts
// as `${toolName} -> ${status}` (or `${toolName} refused: ...`) — swap the raw
// tool name for its operational label while leaving the rest of the sentence
// (and the underlying AuditEvent) untouched.
function readableSummary(event: AuditEvent): string {
  const toolName = event.type === "TOOL_CALL" ? event.detail.toolName : undefined;
  if (typeof toolName !== "string" || !event.summary.startsWith(toolName)) return event.summary;
  return event.summary.replace(toolName, toolCallLabel(toolName));
}

// Left-edge accent per AuditEvent.type — lets a judge scan the shape of a run
// (state changes vs. tool calls vs. the one human action) without reading
// every row's text first. Purely a display grouping; no new data.
const TYPE_ACCENT: Record<AuditEvent["type"], string> = {
  STATE_TRANSITION: "border-l-sky-400",
  TOOL_CALL: "border-l-zinc-300",
  LLM_CALL: "border-l-violet-400",
  VALIDATION: "border-l-amber-400",
  HUMAN_ACTION: "border-l-emerald-400"
};

export function AuditTimeline({ auditEvents }: { auditEvents: AuditEvent[] }): React.ReactElement {
  const chronological = [...auditEvents].sort(
    (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
  );

  return (
    <Panel title="Audit Timeline" subtitle="Gapless chronological event chain — every step, no gaps (§25)">
      <ol className="scroll-thin max-h-80 space-y-1 overflow-y-auto pr-1">
        {chronological.map((event) => (
          <li
            key={event.id}
            className={`flex items-start gap-2.5 border-b border-l-2 border-b-zinc-100 py-2 pl-2.5 text-xs ${TYPE_ACCENT[event.type]}`}
          >
            <span className="w-20 shrink-0 font-mono text-zinc-400">{formatTimeUTC(event.timestamp)} UTC</span>
            <span className="w-8 shrink-0 font-mono text-zinc-400">c{event.cycle}</span>
            <span className="w-14 shrink-0 text-zinc-400">{event.actor}</span>
            <span className="w-32 shrink-0 font-mono text-zinc-400">{event.type}</span>
            <span className="flex-1 text-zinc-700">{readableSummary(event)}</span>
            {isToolStatus(event.detail.status) && (
              <StatusPill label={event.detail.status} tone={toolResultTone(event.detail.status)} />
            )}
          </li>
        ))}
        {chronological.length === 0 && <li className="text-xs text-zinc-400">No audit events yet.</li>}
      </ol>
    </Panel>
  );
}
